#+title: Config
#+tangle: yes

* Table of Contents :toc:
- [[#general-information][General information]]
- [[#fish-things][Fish things]]
- [[#username-and-email-adress][Username and email adress]]
- [[#fonts][Fonts]]
- [[#theme][Theme]]
- [[#line-numbers][Line numbers]]
- [[#start-fullscreen][Start fullscreen]]
- [[#org-mode][Org-mode]]
  - [[#file-location][File Location]]
  - [[#org-roam][org-roam]]
- [[#elixir-config][Elixir config]]
  - [[#workaround-to-enable-running-credo-after-lsp][Workaround to enable running credo after lsp]]
  - [[#configure-elixir-lsp][Configure elixir-lsp]]

* General information
This is the doom emacs config org file from Friedrich Pfitzmann.

To convert this file into a `config.el` one has to do the following steps:

And don't forget to run `doom sync` after configuration changes!

* Fish things
#+begin_src emacs-lisp :tangle yes
(setq shell-file-name (executable-find "bash"))
(setq-default vterm-shell (executable-find "fish"))
(setq-default explicit-shell-file-name (executable-find "fish"))
#+end_src

* Username and email adress
This is taken over of the default config. I do not use it at the moment

Some functionality uses this to identify you, e.g. GPG configuration, email
clients, file templates and snippets. It is optional.

#+begin_src emacs-lisp
;; (setq user-full-name "John Doe"
;;       user-mail-address "john@doe.com")
#+end_src

#+RESULTS:

* Fonts
Doom exposes five (optional) variables for controlling fonts in Doom:

- `doom-font' -- the primary font to use
- `doom-variable-pitch-font' -- a non-monospace font (where applicable)
- `doom-big-font' -- used for `doom-big-font-mode'; use this for
  presentations or streaming.
- `doom-symbol-font' -- for symbols
- `doom-serif-font' -- for the `fixed-pitch-serif' face

See 'C-h v doom-font' for documentation and more examples of what they
accept. For example:

#+begin_src emacs-lisp :tangle yes
(setq doom-font (font-spec :family "Fira Code" :size 18)
      doom-variable-pitch-font (font-spec :family "Fira Sans" :size 18))
;; (setq doom-font (font-spec :family "Fira Code" :size 18 :weight 'regular)
;;       doom-variable-pitch-font (font-spec :family "Fira Sans" :size 18))
#+end_src

If you or Emacs can't find your font, use 'M-x describe-font' to look them
up, `M-x eval-region' to execute elisp code, and 'M-x doom/reload-font' to
refresh your font settings. If Emacs still can't find your font, it likely
wasn't installed correctly. Font issues are rarely Doom issues!

* Theme
I personnally use the catppuccin mocca theme almost everywere.

I followed the instructions on the [https://github.com/catppuccin/emacs#doom-emacs](Catppucin Website).
!!! Do not forget to install the catpuccin package !!!

#+begin_src emacs-lisp :tangle yes
(setq doom-theme 'catppuccin)
#+end_src

* Line numbers
This determines the style of line numbers in effect. If set to `nil', line
numbers are disabled. For relative line numbers, set this to `relative'.

#+begin_src emacs-lisp :tangle yes
(setq display-line-numbers-type 'relative)
#+end_src

* Start fullscreen
#+begin_src emacs-lisp :tangle yes
(add-hook 'window-setup-hook #'toggle-frame-fullscreen)
#+end_src

* Org-mode
Of course I do use the org mode :).

The following line ensures, that the config is not overwritten by the default `org` config.

#+begin_src emacs-lisp :tangle yes
(after! org
#+end_src

** File Location
If you use `org' and don't want your org files in the default location below,
change `org-directory'. It must be set before org loads!

#+begin_src emacs-lisp :tangle yes
(setq org-directory "~/Documents/org/")
(setq org-agenda-files (quote ("~/Documents/org" "~/Documents/org/daily" "~/Documents/org/agendas/2024" "~/Documents/org/journal")))
(setq org-log-done 'time)
(setq org-log-into-drawer t)

;; config for my todo system
(setq org-todo-keywords
      (quote ((sequence "TODO(t)" "NEXT(n)" "|" "DONE(d)")
              (sequence "WAITING(w@/!)" "HOLD(h@/!)" "|" "CANCELLED(c@/!)" "PHONE" "MEETING"))))

(setq org-todo-keyword-faces
      (quote (("TODO" :foreground "red" :weight bold)
              ("NEXT" :foreground "blue" :weight bold)
              ("DONE" :foreground "forest green" :weight bold)
              ("WAITING" :foreground "orange" :weight bold)
              ("HOLD" :foreground "magenta" :weight bold)
              ("CANCELLED" :foreground "forest green" :weight bold)
              ("MEETING" :foreground "forest green" :weight bold)
              ("PHONE" :foreground "forest green" :weight bold))))

(setq org-capture-templates
      `(
        ("t" "Tasks / Projects")
        ("tt" "Task" entry (file+olp "~/Documents/org/20240117083629-refile.org" "Inbox")
         "* TODO %?\n  %U\n  %a\n  %i" :empty-lines 1)
        ("ts" "Clocked Entry Subtask" entry (clock)
         "* TODO %?\n  %U\n  %a\n  %i" :empty-lines 1)
        )
      )
)
#+end_src

** org-roam
I do use org-roam to build my second brain with a Zettelkasten method.

#+begin_src emacs-lisp :tangle no
(use-package org-roam
  :ensure t
  :custom
  (org-roam-directory (file-truename "~/Documents/org/"))
  (org-roam-capture-templates
   '(
     ("d" "default" plain
      (file "~/Documents/org/templates/default.org")
      :if-new (file+head "%<%Y%m%d%H%M%S>-${slug}.org" "#+title: ${title}\n#+date:%U")
      :unnarrowed t)
     ("M" "monthly" plain
      (file "~/Documents/org/templates/monthly.org")
      :if-new (file+head "%<%Y%m%d%H%M%S>-%<%Y-%m>-monthly.org" "")
      :unnarrowed t)
     ("D" "Scrum daily" plain
      (file "~/Documents/org/templates/daily.org")
      :if-new (file+head "./scrum/%<%Y>/%<%Y%m%d%H%M%S>-daily.org" "")
      :unnarrowed t)
     ("r" "scrum refinement" plain
      (file "~/Documents/org/templates/refinement.orgi" )
      :if-new (file+head "./scrum/%<%Y>/%<%Y%m%d%H%M%S>-refinement.org" "")
      :unnarrowed t)
     ("R" "Scrum retro" plain
      (file "~/Documents/org/templates/retro.org")
      :if-new (file+head "./scrum/%<%Y>/%<%Y%m%d%H%M%S>-retro.org" "#+title: ${title}\n#+date:%U")
      :unnarrowed t)
     ("m" "meeting" plain
      (file "~/Documents/org/templates/meeting.org")
      :if-new (file+head "%<%Y%m%d%H%M%S>-meeting-${slug}.org" "")
      :unnarrowed t)
     ("p" "phone call" plain
      (file "~/Documents/org/templates/phone_call.org")
      :if-new (file+head "%<%Y%m%d%H%M%S>-phone-${slug}.org" "#+title: ${title}\n#+date:%U")
      :unnarrowed t)
     ("P" "Project" plain
      (file "~/Documents/org/templates/project.org")
      :if-new (file+head "./projects/%<%Y%m%d%H%M%S>${slug}.org" "#+title: ${title}\n#+date:%U")
      :unnarrowed t)
     ("c" "Collection" plain
      (file "~/Documents/org/templates/collection.org")
      :if-new (file+head "./collection/%<%Y%m%d%H%M%S>${slug}.org" "#+title: ${title}\n#+date:%U")
      :unnarrowed t)
     )
   )
  :bind (("C-c n l" . org-roam-buffer-toggle)
         ("C-c n f" . org-roam-node-find)
         ("C-c n g" . org-roam-graph)
         ("C-c n i" . org-roam-node-insert)
         ("C-c n c" . org-roam-capture)
         ;; Dailies
         ("C-c n j" . org-roam-dailies-capture-today))
  :config
  ;; If you're using a vertical completion framework, you might want a more informative completion interface
  (setq org-roam-node-display-template (concat "${title:*} " (propertize "${tags:10}" 'face 'org-tag)))
  (org-roam-db-autosync-mode)
  ;; If using org-roam-protocol
  (require 'org-roam-protocol)
))
#+end_src

* Elixir config
** Workaround to enable running credo after lsp
#+begin_src emacs-lisp :tangle yes
(defvar-local my/flycheck-local-cache nil)
(defun my/flycheck-checker-get (fn checker property)
  (or (alist-get property (alist-get checker my/flycheck-local-cache))
      (funcall fn checker property)))
(advice-add 'flycheck-checker-get :around 'my/flycheck-checker-get)
(add-hook 'lsp-managed-mode-hook
          (lambda ()
            (when (derived-mode-p 'elixir-mode)
              (setq my/flycheck-local-cache '((lsp . ((next-checkers . (elixir-credo)))))))
            ))
#+end_src

** Configure elixir-lsp
#+begin_src emacs-lisp :tangle yes
(setq lsp-elixir-fetch-deps nil)
(setq lsp-elixir-suggest-specs t)
(setq lsp-elixir-signature-after-complete t)
(setq lsp-elixir-enable-test-lenses t)

*** Set global LSP Options

#+begin_src emacs-lisp :tangle yes
(after! lsp-mode
 (after! lsp-mode (
setq lsp-lens-enable t
lsp-ui-peek-enable t
lsp-ui-doc-enable nil
lsp-ui-doc-position 'bottom
lsp-ui-doc-max-height 70
lsp-ui-doc-max-width 150
lsp-ui-sideline-show-diagnostics t
lsp-ui-sideline-show-hover nil
lsp-ui-sideline-show-code-actions t
lsp-ui-sideline-diagnostic-max-lines 20
lsp-ui-sideline-ignore-duplicate t
lsp-ui-sideline-enable t))
#+end_src
#+begin_src

(setq denote-directory (expand-file-name "~/Documents/org/"))
(setq denote-known-keywords '("emacs" "philosophy" "politics" "economics"))
(setq denote-infer-keywords t)
(setq denote-sort-keywords t)
(setq denote-file-type nil) ; Org is the default, set others here
(setq denote-prompts '(title keywords))
(setq denote-excluded-directories-regexp nil)
(setq denote-excluded-keywords-regexp nil)
#+end_src

*** Denote
#+begin_src emacs-lisp :tangle yes
;; Remember to check the doc strings of those variables.
(setq denote-directory (expand-file-name "~/Documents/org/"))
(setq denote-known-keywords '("emacs" "philosophy" "politics" "economics"))
(setq denote-prompts '(title keywords))
(setq denote-excluded-directories-regexp nil)
(setq denote-excluded-keywords-regexp nil)

;; Pick dates, where relevant, with Org's advanced interface:
(setq denote-date-prompt-use-org-read-date t)


;; Read this manual for how to specify `denote-templates'.  We do not
;; include an example here to avoid potential confusion.


(setq denote-date-format nil) ; read doc string

;; By default, we do not show the context of links.  We just display
;; file names.  This provides a more informative view.
(setq denote-backlinks-show-context t)

;; Also see `denote-link-backlinks-display-buffer-action' which is a bit
;; advanced.

;; If you use Markdown or plain text files (Org renders links as buttons
;; right away)
(add-hook 'find-file-hook #'denote-link-buttonize-buffer)

;; We use different ways to specify a path for demo purposes.
;; (setq denote-dired-directories
;;       (list denote-directory
;;             (thread-last denote-directory (expand-file-name "attachments"))
;;             (expand-file-name "~/Documents/books")))

;; Generic (great if you rename files Denote-style in lots of places):
;; (add-hook 'dired-mode-hook #'denote-dired-mode)
;;
;; OR if only want it in `denote-dired-directories':
(add-hook 'dired-mode-hook #'denote-dired-mode-in-directories)


;; Automatically rename Denote buffers using the `denote-rename-buffer-format'.
(denote-rename-buffer-mode 1)

;; Denote DOES NOT define any key bindings.  This is for the user to
;; decide.  For example:
(let ((map global-map))
  (define-key map (kbd "C-c n n") #'denote)
  (define-key map (kbd "C-c n c") #'denote-region) ; "contents" mnemonic
  (define-key map (kbd "C-c n N") #'denote-type)
  (define-key map (kbd "C-c n d") #'denote-date)
  (define-key map (kbd "C-c n z") #'denote-signature) ; "zettelkasten" mnemonic
  (define-key map (kbd "C-c n s") #'denote-subdirectory)
  (define-key map (kbd "C-c n t") #'denote-template)
  ;; If you intend to use Denote with a variety of file types, it is
  ;; easier to bind the link-related commands to the `global-map', as
  ;; shown here.  Otherwise follow the same pattern for `org-mode-map',
  ;; `markdown-mode-map', and/or `text-mode-map'.
  (define-key map (kbd "C-c n i") #'denote-link) ; "insert" mnemonic
  (define-key map (kbd "C-c n I") #'denote-add-links)
  (define-key map (kbd "C-c n b") #'denote-backlinks)
  (define-key map (kbd "C-c n f f") #'denote-find-link)
  (define-key map (kbd "C-c n f b") #'denote-find-backlink)
  ;; Note that `denote-rename-file' can work from any context, not just
  ;; Dired bufffers.  That is why we bind it here to the `global-map'.
  (define-key map (kbd "C-c n r") #'denote-rename-file)
  (define-key map (kbd "C-c n R") #'denote-rename-file-using-front-matter))

;; Key bindings specifically for Dired.
(let ((map dired-mode-map))
  (define-key map (kbd "C-c C-d C-i") #'denote-link-dired-marked-notes)
  (define-key map (kbd "C-c C-d C-r") #'denote-dired-rename-files)
  (define-key map (kbd "C-c C-d C-k") #'denote-dired-rename-marked-files-with-keywords)
  (define-key map (kbd "C-c C-d C-R") #'denote-dired-rename-marked-files-using-front-matter))

(with-eval-after-load 'org-capture
  (setq denote-org-capture-specifiers "%l\n%i\n%?")
  (add-to-list 'org-capture-templates
               '("n" "New note (with denote.el)" plain
                 (file denote-last-path)
                 #'denote-org-capture
                 :no-save t
                 :immediate-finish nil
                 :kill-buffer t
                 :jump-to-captured t)))

;; Also check the commands `denote-link-after-creating',
;; `denote-link-or-create'.  You may want to bind them to keys as well.


;; If you want to have Denote commands available via a right click
;; context menu, use the following and then enable
;; `context-menu-mode'.
(add-hook 'context-menu-functions #'denote-context-menu)
#+end_src
